--- 
- name: Populate users from a file
  hosts: servera.lab.example.com
  gather_facts: false
  become: true

  tasks:

    - name: Ensure users are at defined state
      vars:
        my_password: "{{ lookup('ansible.builtin.password', 'credentials/' + item + ' length=9') }}"
      loop: "{{ query('ansible.builtin.lines', 'cat users.txt') }}"
      ansible.builtin.user:
        name: "{{ item }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_password | password_hash('sha512') }}"
        groups: "{{ my_groups | default(omit) }}"
        update_password: on_create
